name: Lint Markdown documents

on:
  push:
    paths:
      - '**.md'

jobs:
  markdown-lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint Markdown sources
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.json'
          args: './'
