name: Check URLs in Markdown documents

on:
  push:
    paths:
      - '**.md'
      - '.github/workflows/urlchecker.yml'

jobs:
  urlchecker:
    name: Check URLs in Markdown documents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check URLs in Markdown documents
        uses: urlstechie/urlchecker-action@0.0.27
        with:
          file_types: .md
          exclude_patterns: localhost
